class PLAYPLAY_CTX:
    SIZE = 0x308

    OFF_INITIALIZED = 0x000
    OFF_STATE       = 0x004
    OFF_KEYSTREAM   = 0x2EC
    OFF_BLOCK_INDEX = 0x2FC
    OFF_SETUP_VALUE = 0x300
    OFF_READY_FLAG  = 0x304

    INITIALIZED_SIZE = 1
    STATE_SIZE       = 744
    KEYSTREAM_SIZE   = 16
    BLOCK_INDEX_SIZE = 4
    SETUP_VALUE_SIZE = 4
    READY_FLAG_SIZE  = 4


assert PLAYPLAY_CTX.SIZE == 0x308
