# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spotify_dl_cli/clt_extended_metadata/audio_files_extension.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'spotify_dl_cli/clt_extended_metadata/audio_files_extension.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spotify_dl_cli.clt_extended_metadata import extendedmetadata_pb2 as spotify__dl__cli_dot_clt__extended__metadata_dot_extendedmetadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@spotify_dl_cli/clt_extended_metadata/audio_files_extension.proto\x12#spotify.extendedmetadata.audiofiles\x1a;spotify_dl_cli/clt_extended_metadata/extendedmetadata.proto\"@\n\x13NormalizationParams\x12\x13\n\x0bloudness_db\x18\x01 \x01(\x02\x12\x14\n\x0ctrue_peak_db\x18\x02 \x01(\x02\"k\n\x11\x45xtendedAudioFile\x12\x31\n\x04\x66ile\x18\x01 \x01(\x0b\x32#.spotify.extendedmetadata.AudioFile\x12\x17\n\x0f\x61verage_bitrate\x18\x04 \x01(\x05J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\"\xc1\x02\n\x1b\x41udioFilesExtensionResponse\x12\x45\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x36.spotify.extendedmetadata.audiofiles.ExtendedAudioFile\x12\x63\n!default_file_normalization_params\x18\x02 \x01(\x0b\x32\x38.spotify.extendedmetadata.audiofiles.NormalizationParams\x12\x64\n\"default_album_normalization_params\x18\x03 \x01(\x0b\x32\x38.spotify.extendedmetadata.audiofiles.NormalizationParams\x12\x10\n\x08\x61udio_id\x18\x04 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotify_dl_cli.clt_extended_metadata.audio_files_extension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALIZATIONPARAMS']._serialized_start=166
  _globals['_NORMALIZATIONPARAMS']._serialized_end=230
  _globals['_EXTENDEDAUDIOFILE']._serialized_start=232
  _globals['_EXTENDEDAUDIOFILE']._serialized_end=339
  _globals['_AUDIOFILESEXTENSIONRESPONSE']._serialized_start=342
  _globals['_AUDIOFILESEXTENSIONRESPONSE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
