class PLAYPLAY_CTX:

    OFF_INITIALIZED = 0x000
    OFF_STATE = 0x004
    OFF_KEYSTREAM = 0x2EC
    OFF_BLOCK_INDEX = 0x2FC
    OFF_SETUP_VALUE = 0x300
    OFF_READY_FLAG = 0x304

    INITIALIZED_SIZE = 4
    STATE_SIZE = 744
    KEYSTREAM_SIZE = 16
    BLOCK_INDEX_SIZE = 4
    SETUP_VALUE_SIZE = 4
    READY_FLAG_SIZE = 4

    SIZE = (
        INITIALIZED_SIZE
        + STATE_SIZE
        + KEYSTREAM_SIZE
        + BLOCK_INDEX_SIZE
        + SETUP_VALUE_SIZE
        + READY_FLAG_SIZE
    )


assert PLAYPLAY_CTX.SIZE == 0x308
