// This file is @generated by prost-build.
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageResolveResponse {
    #[prost(enumeration = "storage_resolve_response::Result", tag = "1")]
    pub result: i32,
    #[prost(string, repeated, tag = "2")]
    pub cdnurl: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "4")]
    pub fileid: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `StorageResolveResponse`.
pub mod storage_resolve_response {
    #[derive(serde::Deserialize, serde::Serialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Result {
        Cdn = 0,
        Storage = 1,
        Restricted = 3,
    }
    impl Result {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Result::Cdn => "CDN",
                Result::Storage => "STORAGE",
                Result::Restricted => "RESTRICTED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CDN" => Some(Self::Cdn),
                "STORAGE" => Some(Self::Storage),
                "RESTRICTED" => Some(Self::Restricted),
                _ => None,
            }
        }
    }
}
