// This file is @generated by prost-build.
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayPlayLicenseRequest {
    #[prost(int32, optional, tag = "1")]
    pub version: ::core::option::Option<i32>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub token: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub cache_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(enumeration = "Interactivity", optional, tag = "4")]
    pub interactivity: ::core::option::Option<i32>,
    #[prost(enumeration = "ContentType", optional, tag = "5")]
    pub content_type: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "6")]
    pub timestamp: ::core::option::Option<i64>,
}
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayPlayLicenseResponse {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub obfuscated_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Interactivity {
    UnknownInteractivity = 0,
    Interactive = 1,
    Download = 2,
}
impl Interactivity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Interactivity::UnknownInteractivity => "UNKNOWN_INTERACTIVITY",
            Interactivity::Interactive => "INTERACTIVE",
            Interactivity::Download => "DOWNLOAD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_INTERACTIVITY" => Some(Self::UnknownInteractivity),
            "INTERACTIVE" => Some(Self::Interactive),
            "DOWNLOAD" => Some(Self::Download),
            _ => None,
        }
    }
}
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ContentType {
    UnknownContentType = 0,
    AudioTrack = 1,
    AudioEpisode = 2,
    AudioAdd = 3,
}
impl ContentType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ContentType::UnknownContentType => "UNKNOWN_CONTENT_TYPE",
            ContentType::AudioTrack => "AUDIO_TRACK",
            ContentType::AudioEpisode => "AUDIO_EPISODE",
            ContentType::AudioAdd => "AUDIO_ADD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_CONTENT_TYPE" => Some(Self::UnknownContentType),
            "AUDIO_TRACK" => Some(Self::AudioTrack),
            "AUDIO_EPISODE" => Some(Self::AudioEpisode),
            "AUDIO_ADD" => Some(Self::AudioAdd),
            _ => None,
        }
    }
}
