# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clt_playlist/lens-model.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'clt_playlist/lens-model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63lt_playlist/lens-model.proto\x12\x18spotify.lens.model.proto\"\x1a\n\x04Lens\x12\x12\n\nidentifier\x18\x01 \x01(\t\"1\n\tLensState\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\x0c\x42\x30\n\x1c\x63om.spotify.lens.model.protoB\x0eLensModelProtoH\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clt_playlist.lens_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.spotify.lens.model.protoB\016LensModelProtoH\002'
  _globals['_LENS']._serialized_start=59
  _globals['_LENS']._serialized_end=85
  _globals['_LENSSTATE']._serialized_start=87
  _globals['_LENSSTATE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
